easy_admin:
  site_name: 'B7'
  formats:
    date: 'd/m/Y'
    time: 'H:i'
    datetime: 'd/m/Y H:i:s'

  design:
    templates:
      layout: 'easy_admin_overrides/layout.html.twig'
    menu:
      - { entity: 'Survey', icon: 'question', label: 'menu.survey' }
      - { label: 'menu.admin', role: 'ROLE_ADMIN' }
      - { entity: 'User', icon: 'user', label: 'menu.user' }

  entities:
    User:
      class: App\Entity\User
      role: ROLE_ADMIN
      list:
        fields:
          - { property: 'username', label: 'entity.user.username' }
          - { property: 'email', label: 'entity.user.email' }
          - { property: 'enabled', label: 'entity.user.enabled' }
      form:
        fields:
          - username
          - email
          - enabled
          - lastLogin
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
    Survey:
      class: App\Entity\Survey
      role: ROLE_USER
      list:
        actions:
          - { name: 'redirectToSurvey', label: 'action.redirect_to_survey' }
          - { name: 'statistics', label: 'action.statistics' }
        fields:
          - id
          - { property: 'title', label: 'entity.survey.title' }
          - { property: 'question', label: 'entity.survey.question' }
          - { property: 'responses', label: 'entity.survey.responses' }
          - { property: 'user', role: ROLE_ADMIN, label: 'entity.survey.user' }
      form:
        fields:
          - { property: 'title', label: 'entity.survey.title' }
          - { property: 'question', label: 'entity.survey.question' }
          - { property: 'positiveFollowUp', label: 'entity.survey.positive_follow_up' }
          - { property: 'negativeFollowUp', label: 'entity.survey.negative_follow_up' }
          - { property: 'followUpText1', label: 'entity.survey.follow_up_text_1' }
          - { property: 'followUpText2', label: 'entity.survey.follow_up_text_2' }
          - { property: 'followUpText3', label: 'entity.survey.follow_up_text_3' }
          - { property: 'followUpText4', label: 'entity.survey.follow_up_text_4' }
          - { property: 'followUpText5', label: 'entity.survey.follow_up_text_5' }
          - { property: 'user', role: ROLE_ADMIN, label: 'entity.survey.user' }