easy_admin:
  site_name: 'B7'
  formats:
    date: 'd/m/Y'
    time: 'H:i'
    datetime: 'd/m/Y H:i:s'

  design:
    templates:
      layout: 'easy_admin_overrides/layout.html.twig'
    menu:
      - { entity: 'Survey', icon: 'question', label: 'menu.survey' }
      - { label: 'menu.admin', role: 'ROLE_ADMIN' }
      - { entity: 'User', icon: 'user', label: 'menu.user' }

  entities:
    User:
      class: App\Entity\User
      role: ROLE_ADMIN
      form:
        fields:
          - username
          - email
          - enabled
          - lastLogin
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
    Survey:
      class: App\Entity\Survey
      role: ROLE_USER
      list:
        fields:
          - id
          - title
          - question
          - { property: 'user', role: ROLE_ADMIN }
      form:
        fields:
          - title
          - question
          - positive_follow_up
          - negative_follow_up
          - follow_up_text_1
          - follow_up_text_2
          - follow_up_text_3
          - follow_up_text_4
          - follow_up_text_5
          - { property: 'user', role: ROLE_ADMIN }