easy_admin:
  site_name: 'B7'
  formats:
    date: 'd/m/Y'
    time: 'H:i'
    datetime: 'd/m/Y H:i:s'

  design:
    templates:
      layout: 'easy_admin_overrides/layout.html.twig'
    menu:
      - { entity: 'Survey', icon: 'question', label: 'menu.survey', default: true }
      - { entity: 'Response', icon: 'smile-o', label: 'menu.response'}
      - { label: 'menu.survey_explanation', route: 'survey.explanation' }
      - { label: 'menu.admin', role: 'ROLE_ADMIN' }
      - { entity: 'User', icon: 'user', label: 'menu.user' }

  entities:
    User:
      class: App\Entity\User
      role: ROLE_ADMIN
      list:
        fields:
          - { property: 'username', label: 'entity.user.username' }
          - { property: 'email', label: 'entity.user.email' }
          - { property: 'enabled', label: 'entity.user.enabled' }
      form:
        fields:
          - username
          - email
          - enabled
          - lastLogin
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
    Survey:
      class: App\Entity\Survey
      role: ROLE_USER
      list:
        actions:
          - { name: 'redirectToSurvey', label: 'action.redirect_to_survey' }
          - { name: 'statistics', label: 'action.statistics' }
        fields:
          - id
          - { property: 'title', label: 'entity.survey.title' }
          - { property: 'question', label: 'entity.survey.question' }
          - { property: 'responses', label: 'entity.survey.responses' }
          - { property: 'user', role: ROLE_ADMIN, label: 'entity.survey.user' }
      form:
        fields:
          - { property: 'title', label: 'entity.survey.title', help: 'entity.survey.title_help' }
          - { property: 'question', label: 'entity.survey.question', help: 'entity.survey.question_help' }
          - { property: 'positiveFollowUp', label: 'entity.survey.positive_follow_up', help: 'entity.survey.positive_follow_up_help' }
          - { property: 'neutralFollowUp', label: 'entity.survey.neutral_follow_up', help: 'entity.survey.neutral_follow_up_help' }
          - { property: 'negativeFollowUp', label: 'entity.survey.negative_follow_up', help: 'entity.survey.negative_follow_up_help' }
          - { property: 'followUpText1', label: 'entity.survey.follow_up_text_1', help: 'entity.survey.follow_up_text_help' }
          - { property: 'followUpText2', label: 'entity.survey.follow_up_text_2', help: 'entity.survey.follow_up_text_help' }
          - { property: 'followUpText3', label: 'entity.survey.follow_up_text_3', help: 'entity.survey.follow_up_text_help' }
          - { property: 'followUpText4', label: 'entity.survey.follow_up_text_4', help: 'entity.survey.follow_up_text_help' }
          - { property: 'followUpText5', label: 'entity.survey.follow_up_text_5', help: 'entity.survey.follow_up_text_help' }
          - { property: 'user', role: ROLE_ADMIN, label: 'entity.survey.user' }
    Response:
      class: App\Entity\Response
      role: ROLE_USER
      list:
        actions: ['-new', '-edit', 'show']
        batch_actions: [{ name: 'delete', ask_confirm: true }]
        fields:
          - id
          - { property: 'answer', label: 'entity.response.answer' }
          - { property: 'followUpAnswer', label: 'entity.response.follow_up_answer' }
          - { property: 'createdAt', label: 'entity.response.created_at' }
          - { property: 'survey', label: 'entity.response.survey' }
      show:
        actions: ['-edit']
