easy_admin:
  site_name: 'B7'
  formats:
    date: 'd/m/Y'
    time: 'H:i'
    datetime: 'd/m/Y H:i:s'

  design:
    menu:
      - Product
      - { label: 'menu.admin', role: 'ROLE_ADMIN' }
      - { entity: 'User', icon: 'user', label: 'menu.user' }

  entities:
    User:
      class: App\Entity\User
      role: ROLE_ADMIN
      form:
        fields:
          - username
          - email
          - enabled
          - lastLogin
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
